use_frameworks!

platform :ios, '13.0'

target 'FloatingViewProtocol_Example' do
  pod 'FloatingViewProtocol', :path => '../'

  target 'FloatingViewProtocol_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
